export enum ColorId {
    Default = 1,
    BoldBlue = 2,
    BoldTeal = 3,
    BoldGreen = 4,
    BoldOrange = 5,
    BoldRed = 6,
    BoldPurple = 7,
    Gray = 8,
    Blue = 9,
    Teal = 10,
    Green = 11,
    Orange = 12,
    Red = 13,
    Purple = 14,
    White = 15,
    SubtleBlue = 16,
    SubtleTeal = 17,
    SubtleGreen = 18,
    SubtleYellow = 19,
    SubtlePurple = 20,
}

export enum ColorTitle {
    Default = 'Default',
    BoldBlue = 'Bold blue',
    BoldTeal = 'Bold teal',
    BoldGreen = 'Bold green',
    BoldOrange = 'Bold orange',
    BoldRed = 'Bold red',
    BoldPurple = 'Bold purple',
    Gray = 'Gray',
    Blue = 'Blue',
    Teal = 'Teal',
    Green = 'Green',
    Orange = 'Orange',
    Red = 'Red',
    Purple = 'Purple',
    White = 'White',
    SubtleBlue = 'Subtle blue',
    SubtleTeal = 'Subtle teal',
    SubtleGreen = 'Subtle green',
    SubtleYellow = 'Subtle yellow',
    SubtlePurple = 'Subtle purple',
}

export enum ColorValue {
    Default = '#292A2E',
    BoldBlue = '#1558BC',
    BoldTeal = '#206A83',
    BoldGreen = '#216E4E',
    BoldOrange = '#E06C00',
    BoldRed = '#AE2E24',
    BoldPurple = '#803FA5',
    Gray = '#7D818A',
    Blue = '#357DE8',
    Teal = '#2898BD',
    Green = '#22A06B',
    Orange = '#FCA700',
    Red = '#C9372C',
    Purple = '#AF59E1',
    White = '#FFFFFF',
    SubtleBlue = '#CFE1FD',
    SubtleTeal = '#C6EDFB',
    SubtleGreen = '#BAF3DB',
    SubtleYellow = '#F5E989',
    SubtlePurple = '#EED7FC',
}
