import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import { cookies } from 'next/headers';
import { Header } from '@/components/Header';
import ThemeProviderWrapper from '@/core/providers/ThemeProviderWrapper';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const themeCookie = cookieStore.get('theme');
    const currentTheme = themeCookie?.value || 'light';

    return (
        <html lang="en" data-theme={currentTheme}>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ThemeProviderWrapper>
                    <Header />
                    {children}
                </ThemeProviderWrapper>
            </body>
        </html>
    );
}
