name: Next.js CI with pnpm (Windows)

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']

jobs:
    build-test:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build Next.js app
              working-directory: ./kanban-pro
              run: pnpm run build

            - name: Run tests
              working-directory: ./kanban-pro
              run: pnpm run test
